package com.hellocorp.example.iam.test.dao;

import com.hellocorp.example.iam.IamApplication;
import com.hellocorp.example.iam.infra.persist.bk.RoleBK;
import com.hellocorp.example.iam.infra.persist.dao.RoleDAO;
import com.hellocorp.example.iam.infra.persist.dataobject.RoleDO;
import com.hellocorp.example.iam.infra.persist.query.RoleOffsetQuery;
import com.hellocorp.example.iam.infra.persist.query.RolePageNumQuery;
import jakarta.annotation.Resource;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * auto generated by erplant.
 */
@SpringBootTest(
        classes = IamApplication.class
)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class RoleDaoTest {
    @Resource
    private RoleDAO roleDAO;

    private final String name = "hah";

    private final String bizType = "hgd";

    @Test
    @Order(1)
    public void testInsert() {
        RoleDO roleDO = new RoleDO();
        roleDO.setName(name);
        roleDO.setBizType(bizType);
        int affectRow = roleDAO.insert(roleDO);
        Assertions.assertTrue(affectRow > 0);
    }

    @Test
    @Order(2)
    public void testGet() {
        RoleDO roleDO = roleDAO.getByBk(new RoleBK(bizType, name));
        Assertions.assertNotNull(roleDO);
    }

    @Test
    @Order(2)
    public void testGetByBk() {
        RoleDO roleDO = roleDAO.getByBk(new RoleBK(bizType, name));
        Assertions.assertNotNull(roleDO);
    }

    @Test
    @Order(2)
    public void testPageNumQuery() {
        RolePageNumQuery query = RolePageNumQuery.builder().bizType(bizType).build();
        List<RoleDO> list = roleDAO.pageNumQuery(query);
        Assertions.assertFalse(list.isEmpty());
    }

    @Test
    @Order(2)
    public void testOffsetQuery() {
        RoleOffsetQuery query = RoleOffsetQuery.builder().bizType(bizType).build();
        List<RoleDO> list = roleDAO.offsetQuery(query);
        Assertions.assertFalse(list.isEmpty());
    }

    @Test
    @Order(2)
    public void testCount() {
        RolePageNumQuery query = RolePageNumQuery.builder().bizType(bizType).build();
        int count = roleDAO.count(query);
        Assertions.assertTrue(count > 0);
    }

    @Test
    @Order(3)
    public void testUpdate() {
        RoleDO roleDO = roleDAO.getByBk(new RoleBK(bizType, name));
        roleDO.setName(name);
        roleDO.setBizType(bizType);
        int affectRow = roleDAO.update(roleDO);
        Assertions.assertTrue(affectRow > 0);
    }

    @Test
    @Order(4)
    public void testDelete() {
        RoleDO roleDO = roleDAO.getByBk(new RoleBK(bizType, name));
        int affectRow = roleDAO.delete(roleDO.getId());
        Assertions.assertTrue(affectRow > 0);
    }

    @Test
    @Order(2)
    public void testBatchGet() {
        RoleDO roleDO = roleDAO.getByBk(new RoleBK(bizType, name));
        List<RoleDO> list = roleDAO.batchGet(List.of(roleDO.getId()));
        Assertions.assertFalse(list.isEmpty());
    }
}
